name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    container: 
        image: rdarnley/rsr:common
        credentials:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    defaults:
      run:
        shell: bash
        working-directory: mmpug_ws/

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Build code
      run: |
        pwd
        cd src/mmpug_autonomy/
        pwd
        source /opt/ros/noetic/setup.bash
        echo "hi"
        catkin build


    # source /home/cmu/.mmpug/auto/mmpug_redirect.bash
    # source /home/cmu/.bashrc
    # mmpug deployer local.autonomy.start
    # mmpug deployer local.autonomy.build

    # - name: configure
    #   run: ./configure
    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
